services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: pbureera
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: piscineds
    ports:
      - "5432:5432"
